### ISSUE TITLE
Question about the deploy task. 

### ISSUE THREAD

**Issue by tinchoz49** [shipitjs/shipit-deploy#15]
Hi neoziro! First at all,  excellent tool :+1: you are doing a good job!

I have a question about the deploy process.

Have we a way to make deploys without remoteCopy all the files? Like the tool rocketeer using "rocketeer update"

http://rocketeer.autopergamene.eu/#/docs/docs/IV-Usage/Deploying

Thanks!

**Comment by neoziro** [comment]
@tinchoz49 hi, first sorry to answer 13 days after.. 

It's possible to do something like that with Shipit, but in the "shipit-deploy" task, I choose the way of doing an rsync of the project in local. Why? Simply because in most of my project, I have an heavily build phase (uglify, Babel, etc..) and I don't want to run this on the remote server because it will use CPU and break my service.

So you can do it by inspiring of this task, and create a new deploy workflow.
