### ISSUE TITLE
Allow deployment without git repository

### ISSUE THREAD

**Issue by paulmenzel** [shipitjs/shipit-deploy#24]
In some projects, the files to be deployed are created for example by `gulp build`, creating the directory `dist` with all the files. Deployment in that setup is just to get the files in the folder to the server. Currently such a setup is not supported by shipit-deploy. Basically the fetch task has to be left out.

Is it wanted to support that use case? I could imagine not specifying the parameter `repositoryUrl` and setting the workspace directory to `dist` (`workspace: dist`) would be a possible way to integrate it with the current shipit-deploy configuration.

Would that work or do you see problems with this approach?

**Comment by kargnas** [comment]
+1 I just want to deploy with only Rsync!

**Comment by neoziro** [comment]
@kargnas to do that you must do your own deploy task workflow and remove "deploy:fetch" task, you can replace it by another task if you want.

```js
utils.registerTask(gruntOrShipit, 'deploy2', [
    'deploy:init',
    'deploy:update',
    'deploy:publish',
    'deploy:clean'
  ]);
```

See https://github.com/shipitjs/shipit-deploy/blob/master/tasks/deploy/index.js

**Comment by iMoses** [comment]
+1

I think it's a good idea to keep the `repositoryUrl` optional and if not specified remove the deploy:fetch task.

**Comment by neoziro** [comment]
@iMoses I try to keep Shipit simple, so I prefer that you put additional edge case code in your projects than in Shipit.

**Comment by grEvenX** [comment]
Just wanted to chime in with some thoughts since I had the same challenge recently. What would be nice is if there was a "basis" deploy module that could easily be extended to serve various purposes. When it comes to the `deploy` tasks all of them can easily be used individually to serve flows not related to git deployment in specific (`deploy:init`, `deploy:publish` and `deploy:clean`). There's a lot of nice code there that would serve as a basis for generic deploys.

`deploy:fetch` is all about git functionality and it's easy to orchestrate deployment without it for other uses.
The only problem I had in this case is `deploy:update` which handles the "versioning" and release-paths etc but throws in one additional function `setCurrentRevision` that actually uses git. If it wasn't for that function alone it could be used entirely standalone.

I understand if the authors feels that serving a larger and more generic cause is not the purpose of this module, but as of the current version it would seem possible to move out the `revision` part of the code into separate tasks making it possible to leverage and use this module for more generic purposes (e.g pure local rsync with support for versioning on the server-side).

**Comment by neoziro** [comment]
@grEvenX yes I agree, it would be nice to compose custom deploy task, if you say that only deploy:update is a problem, it can be easy to refactor. If you want to do it in an PR, feel free.
