### ISSUE TITLE
Allow possibility to clone Git repository from server

### ISSUE THREAD

**Issue by welcoMattic** [shipitjs/shipit-deploy#30]
Hi! 
I've got heavy git reposoitories, and it takes a lot of time to copy to the server. 
It might be possible to directly clone git from the server with a command like: 
`shipit.remote.clone ('http://github.com/account/repo);`

This would accelerate the deployment.

Thanks for your work ;)

**Comment by neoziro** [comment]
@welcoMattic yes it was asked a lot of time, feel free to rewrite a deploy script that do that, but for now it's not plan because I don't need it. All of my projects have a lot of build and it's not good to do it on the remote. I think that #19 will solve your problem of speed and you would continue to get the benefit from building locally.

**Comment by welcoMattic** [comment]
@neoziro Ok, I probably will do it later.
