### ISSUE TITLE
Change workspace to be more explicit

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit-deploy#58]
https://github.com/shipitjs/shipit/issues/61

**Comment by tom2strobl** [comment]
+1
I had the same "workspace"-experience as the guy in the other thread, luckily I just boilerplated a new project - yet everything was gone, was pretty mad

**Comment by neoziro** [comment]
@tom2strobl can you propose another name?

**Comment by tom2strobl** [comment]
I don't think it's a naming issue, but a description issue, so for example instead of

```Define the local working path of the project deployed.```

which doesn't really tell me anything about what happens at the path – I'd suggest something around

```Define a path to an empty directory where shipit builds it's syncing source, beware to not set this path to the root of your repository as shipit-deploy cleans the directory at the given path as a first step.```

I think destructive commands as ```rm -rf``` on dynamic paths always demand documentation. I also don't think you can provide *too much* information in the docs.

By the way, once I got the hang of it I thoroughly enjoyed the library. What I really like about the approach is that on the server part you don't really have to install anything, the only dependency really is that you ```ssh``` via key – I wonder if the magic would also be possible with providing a password instead of a keyfile? (as in client projects we're not always allowed to authorize our keys)

Either way, keep it up!
