### ISSUE TITLE
Test coherence before rollback using "REVISION" file

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit-deploy#70]
As discussed in https://github.com/shipitjs/shipit/issues/66, we must use REVISION file to check if servers are synced to be able to rollback.

**Comment by brycefisher** [comment]
Thank you @neoziro! I'll work on a PR for you on this today or tomorrow. Just to recap the plan here:

 * deploy task can be configured NOT to check for releases sync-ed
 * rollback task **must** check the `REVISION` file before attempting a rollback

I'll move forward with the above changes, but feel free to correct me if I've misunderstood the plan here.

**Comment by neoziro** [comment]
@brycefisher for the first point, you can just check if there is an "empty" server and ignore it, we don't need the "NOT to check" option.

**Comment by neoziro** [comment]
So we must use REVISION for check, and if there is no REVISION, ignore it.

**Comment by brycefisher** [comment]
Thanks for clarifying! That does seem a bit easier to do.

**Comment by brycefisher** [comment]
@neoziro I *think* we don't need to check the REVISION. Here's my reasoning:

 * **During a deployment,** new and old servers will get the same release just by ignoring the lack of any prior releases
 * **During a rollback,** a new server can't rollback if it only has one release, so we probably want to stop the rollback then. The [current check in shipit.getReleases()](https://github.com/shipitjs/shipit-deploy/blob/master/tasks/rollback/init.js#L38) will fail [given the current implementation](https://github.com/shipitjs/shipit-deploy/blob/master/lib/shipit.js#L81) which is good because we couldn't rollback that new server coherently.

![shipit-release-logic](https://cloud.githubusercontent.com/assets/220106/8166662/155e4608-134e-11e5-8741-423701775702.png)


What does checking the REVISION give us that checking release doesn't? I'm probably missing something here -- so please correct me if I've got this wrong!

**Comment by neoziro** [comment]
Yes you don't need it, but if you make a deployment in two times it can be a nice feature to be able to rollback.

**Comment by brycefisher** [comment]
That's true -- makes sense. I'll take a crack at using the revision. Thanks @neoziro !

**Comment by dasilvacontin** [comment]
What about copying older release from server to server?

**Comment by neoziro** [comment]
@dasilvacontin it's actually the best thing to do

**Comment by demohi** [comment]
+1 for the feature

**Comment by vjpr** [comment]
+1

**Comment by Marindrew** [comment]
+1

**Comment by Almouro** [comment]
:+1:

**Comment by richardgirges** [comment]
We are using shipit alongside AWS autoscale. So naturally, some servers are spun up with inconsistent releases. The ability to disable strict consistency checks across releases is extremely needed for us. Looking forward to this being resolved...

**Comment by snollygolly** [comment]
+1

**Comment by oesteve** [comment]
+1

**Comment by timkelty** [comment]
@brycefisher did you ever get around to a PR?

**Comment by brycefisher** [comment]
@timkelty I did, but I wasn't able to come up with acceptable solution -- see https://github.com/shipitjs/shipit-deploy/pull/71

I found that I was rewriting pretty major sections of shipit, and it didn't feel quite right. I had hoped to perhaps relax the requirement that rollbacks must always work to keep my code changes simple, but I wasn't able to get traction around that idea.

I feel a little disappointed that I wasn't able to come up with a better solution that addressed all parties concerns for this issue, since it seems like many users shipit felt some pain around this. Perhaps, with a bit more requirement gathering, this issue might have another PR from another member of the shipit user base?

**Comment by timkelty** [comment]
Idea:
@brycefisher what if shipit-deploy provided a synchronize task that synchronized all servers, so you wouldn't have to do it "manually".

**Comment by brycefisher** [comment]
That seems like a very promising idea -- what's the failure scenario like if shipit-deploy can't sync up the revisions directories?

**Comment by neoziro** [comment]
If you want to continue, please open an issue on shipit repository. https://github.com/shipitjs/shipit
